export const projects = [
    {id: 1, location: 'time.php', img: '/img/тупые часы.png', name: 'Время до звонка'},
    {id: 2, location: 'mathematic-logic.php', img: '/img/матлог.png', name: 'Билеты по матлогу'},
    {id: 3, location: 'math-analysis.php', img: '/img/матан.png', name: 'Билеты по матану'},
    {id: 4, location: '/math-analysis-2/index.html', img: '/img/матан2.png', name: 'Вторые билеты по матану'},
    {id: 5, location: '/math-analysis-3', img: '/img/матан3.png', name: 'Билеты по диффурам'},
    {id: 6, location: 'countdown.php', img: '/img/счётчик.png', name: 'Счётчик дней'},
    {id: 7, location: '/getthefuckoff', img: '/img/GetTheFUCKoff.jpg', name: 'GetTheFUCKoff'},
    {id: 8, location: 'pension/', img: '/img/pension.png', name: 'Пенсионный калькулятор'},
    {id: 9, location: '5.php', img: '/img/каблы.png', name: 'Какой вы гендер?'},
    {id: 10, location: 'candle/18.php', img: '/img/nsu-icon.png', name: 'Онлайн-монастырь НГУ'},
    {id: 11, location: 'https://t.me/capcunt_sep_bot', img: '/img/capcunt.png', name: 'CapCunt'},
    {id: 12, location: '/arm', img: '/img/arm.png', name: 'Армянизатор'},
    {id: 13, location: 'natal-chart.php', img: '/img/наталья.jpg', name: 'Натальная карта'},
    {id: 14, location: 'ig.php', img: '/img/холстоклиптоман.png', name: 'Холстоклиптоман'},
    {id: 15, location: 'https://t.me/independent_library_bot', img: '/img/457.jpg', name: 'Независимое издательство'},
    {id: 16, location: 'https://t.me/climate_invest_bot', img: '/img/климат.png', name: 'Климат Инвест Банк'},
    {id: 17, location: '21.php', img: '/img/21.png', name: 'Игра в 21'},
    {id: 18, location: '6.php', img: '/img/хорошо.png', name: 'Сделать всё хорошо'},
    {id: 19, location: 'code.php', img: '/img/цвет.png', name: 'Кодирование в цвет'},
    {id: 20, location: 'rsa.php', img: '/img/rsa.png', name: 'RSA-калькулятор'},
    {id: 21, location: 'comments.php', img: '/img/дневник.png', name: 'Книга пожеланий'},
    {id: 22, location: 'report2025.php', img: '/img/отчёт.png', name: 'Отчёт компании'},
    {id: 23, location: 'https://anal.sepcode.ru', img: '/img/anallogo.svg', name: 'Аналитический центр', isComponent: true},
    {id: 24, location: 'https://vibe.sepcode.ru', img: '/img/vibelogo.svg', name: '+vibe фонд'}
];